from __future__ import annotations

from typing import Any, Protocol

from fpvscan.app.domain.models import Observation, ObservationSchema, Session


class TestStoreProtocol(Protocol):
    async def get_idempotent(self, key: str, operation: str) -> dict[str, Any] | None: ...
    async def put_idempotent(
        self, key: str, operation: str, fingerprint: str, payload: dict[str, Any]
    ) -> None: ...
    async def get_idempotent_fingerprint(self, key: str) -> tuple[str, str] | None: ...

    async def create_session(self, session: Session) -> Session: ...
    async def get_session(self, session_id: str) -> Session | None: ...
    async def list_sessions(self) -> list[Session]: ...
    async def update_session(self, session: Session) -> Session: ...

    async def get_active_schema(self) -> ObservationSchema: ...
    async def get_schema(self, schema_id: str) -> ObservationSchema | None: ...
    async def put_schema(self, schema: ObservationSchema) -> ObservationSchema: ...

    async def create_observation(self, obs: Observation) -> Observation: ...
    async def get_observation(self, session_id: str, obs_id: str) -> Observation | None: ...
    async def list_observations(self, session_id: str) -> list[Observation]: ...
    async def update_observation(self, obs: Observation) -> Observation: ...
    async def delete_observation(self, session_id: str, obs_id: str) -> bool: ...
