from __future__ import annotations

from typing import Any, Protocol


class EnginePort(Protocol):
    def snapshot(self) -> dict[str, Any]: ...
    def current_cfg(self) -> dict[str, Any]: ...
    def default_cfg(self) -> dict[str, Any]: ...
    def yaml_text(self) -> str: ...
    def apply_values(self, values: dict[str, Any]) -> None: ...
    def current_param_values(self) -> dict[str, Any]: ...
    def refresh_lock(self) -> None: ...
